spring:
  application:
    name: productViewShow
  zipkin:
    base-url: http://127.0.0.1:9411
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    content-type: text/html
    mode: HTML5